### ISSUE TITLE
Error 'no module named collector'

### ISSUE THREAD

**Issue by ASL07** [HBehrens/puncover#30]
Hi,
Thanks for the great tool. I am having issues making it work. Hope you can help with it

These are the steps I followed
1. Clone the repo
2. Cd into the repo and run `python setup.py build` and `python setup.py install`
3. Run the following 
`puncover --gcc_tools_base ~/.platformio/packages/toolchain-xtensa --elf /Users/developer/Code/testproject/.pio/build/esp01_1m/firmware.elf --build_dir /Users/developer/Code/testproject/.pio/build --src_root /Users/developer/Code/testproject`
 
I get the following error:
`Traceback (most recent call last):
  File "/usr/local/bin/puncover", line 11, in <module>
    load_entry_point('puncover==0.0.1', 'console_scripts', 'puncover')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/puncover-0.0.1-py3.7.egg/puncover/puncover.py", line 8, in <module>
    from collector import Collector`

**Comment by mjessome** [comment]
Hey @ASL07 , I believe that this is fixed by #28
